### PR TITLE
Vuepress ES to PT fix

### PR DESCRIPTION
**Pull request by ryuzeen**

### CODE REVIEW

**Comment by QweRezOn** [comment]
Conflict file

**Comment by Schvis** [comment]
skill issue fr

**Comment by ryuzeen** [comment]
Not skill issue anymore >:)

**Comment by Schvis** [comment]
Someone had to help you 😠

**Comment by QweRezOn** [comment]
AHAHAHAHAHHAHAHA

**Comment by Schvis** [comment]
LMAO

**Pull request merged**
